apiVersion: v1
kind: ServiceAccount
metadata:
  name: springboot-admin-k8s
  namespace: elk
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: springboot-admin-k8s
subjects:
  - kind: ServiceAccount
    name: springboot-admin-k8s
    namespace: elk
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
