server:
  port: 11000
spring:
  application:
    name: demo-server
eureka:
  client:
    fetch-registry: false #不检索服务
    register-with-eureka: false #不向注册中心注册自己
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/
