server:
  port: 10013
spring:
  application:
    name: auth-server
management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
elk:
  name: elk
