server:
  port: 11001
spring:
  application:
    name: demo-service-b
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/

management:
  info:
    git:
      mode: full
