apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: demo-service-b
spec:
  type: NodePort
  ports:
    - name: server
      port: 8080
      targetPort: 8080
  selector:
    app: demo-service-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service-b
  namespace: elk
  labels:
    name: demo-service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-service-b
  template:
    metadata:
      labels:
        app: demo-service-b
    spec:
      serviceAccountName: springboot-admin-k8s
      containers:
        - name: demo-service-b
          image: elk/demo-service-b:0.0.1-SNAPSHOT
          args: []
          ports:
            - containerPort: 8080
              name: server
