server:
  port: 10012
spring:
  application:
    name: gateway-server
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        tags:
          - service
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
