spring:
  application:
    name: admin-server
  boot:
    admin:
      discovery:
        ignored-services:
          - consul
management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
