server:
  port: 10011
spring:
  application:
    name: admin-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
